# Generated by Django 4.1.1 on 2022-09-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingName',
        ),
    ]
